[package]
name = "thessa-autopilot"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license = "GPL-3.0-or-later"
publish = false

[dependencies]
glam.workspace = true
thessa-flight-control = { path = "../flight-control" }
thessa-sim-core = { path = "../sim-core" }
serde.workspace = true

[dev-dependencies]
serde_json.workspace = true
