//! Machine-readable setting descriptors for the future GUI (spec section 16).
//!
//! The GUI parses/edits the actual `graphics.toml` model. Each descriptor
//! carries path, label, type, range, units, visibility and restart
//! requirements so the GUI never hides the real model behind opaque presets.

use serde::{Deserialize, Serialize};

/// Setting value kind for typed GUI editors.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum SettingKind {
    Bool,
    Float,
    Int,
    Enum,
}

/// One editable setting with GUI metadata.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct SettingMeta {
    /// TOML path, e.g. `atmosphere.ray_steps`.
    pub path: &'static str,
    pub label: &'static str,
    pub kind: SettingKind,
    /// Allowed values for enums, `min..=max` text for numerics.
    pub range: &'static str,
    pub step: &'static str,
    pub unit: &'static str,
    pub advanced: bool,
    pub restart_required: bool,
    pub description: &'static str,
}

/// Descriptors for the core settings. Budgets editable at runtime are
/// `restart_required: false`; backend/mode switches need restart.
pub fn describe() -> Vec<SettingMeta> {
    vec![
        SettingMeta {
            path: "preset",
            label: "Graphics preset",
            kind: SettingKind::Enum,
            range: "low | medium | high | ultra | custom",
            step: "-",
            unit: "-",
            advanced: false,
            restart_required: false,
            description: "Bulk starting point; manual edits report custom.",
        },
        SettingMeta {
            path: "renderer.backend",
            label: "Render backend",
            kind: SettingKind::Enum,
            range: "auto | vulkan | metal | webgpu",
            step: "-",
            unit: "-",
            advanced: true,
            restart_required: true,
            description: "wgpu backend preference. Direct DX paths need an ADR.",
        },
        SettingMeta {
            path: "renderer.ray_tracing",
            label: "Ray tracing mode",
            kind: SettingKind::Enum,
            range: "off | local | full | auto",
            step: "-",
            unit: "-",
            advanced: false,
            restart_required: true,
            description: "Experimental Solari path. Explicit modes fail fast without RT hardware.",
        },
        SettingMeta {
            path: "renderer.terrain",
            label: "Terrain raster path",
            kind: SettingKind::Enum,
            range: "cpu | gpu_indexed",
            step: "-",
            unit: "-",
            advanced: true,
            restart_required: true,
            description: "Choose the portable CPU tile path or the indexed CBT page consumer; mesh shaders are not required.",
        },
        SettingMeta {
            path: "renderer.terrain_mesh_cells",
            label: "Terrain mesh cells",
            kind: SettingKind::Int,
            range: "8..=64",
            step: "4",
            unit: "cells/tile",
            advanced: true,
            restart_required: true,
            description: "CPU terrain grid density per tile edge; higher values cost more CPU/GPU time. Indexed CBT keeps its fixed 32-cell page contract.",
        },
        SettingMeta {
            path: "renderer.resolution_scale",
            label: "Resolution scale",
            kind: SettingKind::Float,
            range: "0.25..=4.0",
            step: "0.05",
            unit: "×",
            advanced: false,
            restart_required: false,
            description: "Render resolution multiplier.",
        },
        SettingMeta {
            path: "renderer.vsync",
            label: "VSync",
            kind: SettingKind::Bool,
            range: "true | false",
            step: "-",
            unit: "-",
            advanced: false,
            restart_required: false,
            description: "Vertical sync.",
        },
        SettingMeta {
            path: "renderer.hdr",
            label: "HDR render target",
            kind: SettingKind::Bool,
            range: "true | false",
            step: "-",
            unit: "-",
            advanced: false,
            restart_required: true,
            description: "Use an intermediate high-dynamic-range camera target for lighting and tone mapping.",
        },
        SettingMeta {
            path: "renderer.auto_exposure",
            label: "Adaptive exposure",
            kind: SettingKind::Bool,
            range: "true | false",
            step: "-",
            unit: "-",
            advanced: false,
            restart_required: true,
            description: "Adapt camera brightness to daylight, night and eclipses; disable for manual EV100.",
        },
        SettingMeta {
            path: "renderer.exposure_ev100",
            label: "Exposure",
            kind: SettingKind::Float,
            range: "1..=20",
            step: "0.5",
            unit: "EV100",
            advanced: true,
            restart_required: false,
            description: "Camera exposure compensation for raw-sun scenes.",
        },
        SettingMeta {
            path: "atmosphere.enabled",
            label: "Atmosphere",
            kind: SettingKind::Bool,
            range: "true | false",
            step: "-",
            unit: "-",
            advanced: false,
            restart_required: false,
            description: "Master switch for visual atmosphere.",
        },
        SettingMeta {
            path: "atmosphere.quality",
            label: "Atmosphere quality",
            kind: SettingKind::Enum,
            range: "low | medium | high",
            step: "-",
            unit: "-",
            advanced: false,
            restart_required: false,
            description: "Budgets only; never changes physics.",
        },
        SettingMeta {
            path: "atmosphere.ray_steps",
            label: "Atmosphere ray steps",
            kind: SettingKind::Int,
            range: "4..=128",
            step: "4",
            unit: "steps",
            advanced: true,
            restart_required: false,
            description: "View-march steps for CPU optical queries.",
        },
        SettingMeta {
            path: "atmosphere.aerial_perspective",
            label: "Aerial perspective",
            kind: SettingKind::Bool,
            range: "true | false",
            step: "-",
            unit: "-",
            advanced: false,
            restart_required: false,
            description: "Apply distance-dependent atmospheric depth and color to scene geometry.",
        },
        SettingMeta {
            path: "atmosphere.density_scale",
            label: "Atmosphere density scale",
            kind: SettingKind::Float,
            range: "0..=2",
            step: "0.05",
            unit: "×",
            advanced: true,
            restart_required: false,
            description: "Visual optical-depth multiplier; does not change simulation pressure or physics.",
        },
        SettingMeta {
            path: "atmosphere.multiple_scattering",
            label: "Multiple scattering",
            kind: SettingKind::Bool,
            range: "true | false",
            step: "-",
            unit: "-",
            advanced: true,
            restart_required: false,
            description: "Reserve the higher-order scattering slice when the renderer supports it.",
        },
        SettingMeta {
            path: "atmosphere.limb_scattering",
            label: "Limb scattering",
            kind: SettingKind::Bool,
            range: "true | false",
            step: "-",
            unit: "-",
            advanced: true,
            restart_required: false,
            description: "Enhance the optically thick planetary limb.",
        },
        SettingMeta {
            path: "atmosphere.sky_dome",
            label: "Sky dome",
            kind: SettingKind::Bool,
            range: "true | false",
            step: "-",
            unit: "-",
            advanced: false,
            restart_required: false,
            description: "Render the atmosphere-derived sky view around the active body.",
        },
        SettingMeta {
            path: "atmosphere.eclipses",
            label: "Eclipse darkening",
            kind: SettingKind::Bool,
            range: "true | false",
            step: "-",
            unit: "-",
            advanced: false,
            restart_required: false,
            description: "Geometric eclipse dimming of direct light and sky.",
        },
        SettingMeta {
            path: "atmosphere.multi_star",
            label: "Multi-star lighting",
            kind: SettingKind::Bool,
            range: "true | false",
            step: "-",
            unit: "-",
            advanced: false,
            restart_required: false,
            description: "Accept secondary-star contribution in the lighting interface.",
        },
        SettingMeta {
            path: "clouds.enabled",
            label: "Clouds",
            kind: SettingKind::Bool,
            range: "true | false",
            step: "-",
            unit: "-",
            advanced: false,
            restart_required: false,
            description: "Enable the separate cloud subsystem when implemented for the active world.",
        },
        SettingMeta {
            path: "clouds.quality",
            label: "Cloud quality",
            kind: SettingKind::Enum,
            range: "low | medium | high",
            step: "-",
            unit: "-",
            advanced: false,
            restart_required: false,
            description: "Cloud sampling budget; never changes atmosphere or physics.",
        },
        SettingMeta {
            path: "clouds.volumetric",
            label: "Volumetric clouds",
            kind: SettingKind::Bool,
            range: "true | false",
            step: "-",
            unit: "-",
            advanced: true,
            restart_required: false,
            description: "Use volume marching rather than a shell representation when available.",
        },
        SettingMeta {
            path: "clouds.ray_steps",
            label: "Cloud ray steps",
            kind: SettingKind::Int,
            range: "4..=128",
            step: "4",
            unit: "steps",
            advanced: true,
            restart_required: false,
            description: "View-march budget for volumetric cloud queries.",
        },
        SettingMeta {
            path: "clouds.cast_shadows",
            label: "Cloud shadows",
            kind: SettingKind::Bool,
            range: "true | false",
            step: "-",
            unit: "-",
            advanced: true,
            restart_required: false,
            description: "Allow clouds to attenuate direct light when cloud shadows are available.",
        },
        SettingMeta {
            path: "upper_atmosphere.airglow",
            label: "Airglow",
            kind: SettingKind::Bool,
            range: "true | false",
            step: "-",
            unit: "-",
            advanced: true,
            restart_required: false,
            description: "Weak night-side upper-atmosphere emission.",
        },
        SettingMeta {
            path: "upper_atmosphere.aurora",
            label: "Aurora shell",
            kind: SettingKind::Bool,
            range: "true | false",
            step: "-",
            unit: "-",
            advanced: true,
            restart_required: false,
            description: "Auroral emission shell, independent of scattering.",
        },
        SettingMeta {
            path: "upper_atmosphere.aurora_quality",
            label: "Aurora quality",
            kind: SettingKind::Enum,
            range: "low | high",
            step: "-",
            unit: "-",
            advanced: true,
            restart_required: false,
            description: "Aurora shell or volumetric-curtain budget.",
        },
        SettingMeta {
            path: "upper_atmosphere.aurora_lighting",
            label: "Aurora lighting",
            kind: SettingKind::Bool,
            range: "true | false",
            step: "-",
            unit: "-",
            advanced: true,
            restart_required: false,
            description: "Allow aurora to participate as an emissive lighting source when supported.",
        },
        SettingMeta {
            path: "raytracing.terrain",
            label: "RT terrain participation",
            kind: SettingKind::Bool,
            range: "true | false",
            step: "-",
            unit: "-",
            advanced: true,
            restart_required: false,
            description: "Include terrain geometry in local/full RT mode.",
        },
        SettingMeta {
            path: "raytracing.vehicles",
            label: "RT vehicle participation",
            kind: SettingKind::Bool,
            range: "true | false",
            step: "-",
            unit: "-",
            advanced: true,
            restart_required: false,
            description: "Include vehicle geometry in local/full RT mode.",
        },
        SettingMeta {
            path: "raytracing.landmarks",
            label: "RT landmark participation",
            kind: SettingKind::Bool,
            range: "true | false",
            step: "-",
            unit: "-",
            advanced: true,
            restart_required: false,
            description: "Include static landmarks in local/full RT mode.",
        },
        SettingMeta {
            path: "raytracing.atmosphere",
            label: "RT atmosphere queries",
            kind: SettingKind::Bool,
            range: "true | false",
            step: "-",
            unit: "-",
            advanced: true,
            restart_required: false,
            description: "Allow RT-aware atmosphere/transmittance queries.",
        },
        SettingMeta {
            path: "raytracing.clouds",
            label: "RT cloud participation",
            kind: SettingKind::Bool,
            range: "true | false",
            step: "-",
            unit: "-",
            advanced: true,
            restart_required: false,
            description: "Include cloud proxies in local/full RT mode.",
        },
        SettingMeta {
            path: "raytracing.max_distance_m",
            label: "RT max distance",
            kind: SettingKind::Float,
            range: "0..=1e9",
            step: "10000",
            unit: "m",
            advanced: true,
            restart_required: false,
            description: "Budget cap for ray-traced participation.",
        },
        SettingMeta {
            path: "debug.show_rt_proxies",
            label: "Show RT proxies",
            kind: SettingKind::Bool,
            range: "true | false",
            step: "-",
            unit: "-",
            advanced: true,
            restart_required: false,
            description: "Visualize the simplified meshes submitted to the local RT path.",
        },
        SettingMeta {
            path: "debug.show_atmosphere_bounds",
            label: "Show atmosphere bounds",
            kind: SettingKind::Bool,
            range: "true | false",
            step: "-",
            unit: "-",
            advanced: true,
            restart_required: false,
            description: "Debug visualization of the optical shell.",
        },
        SettingMeta {
            path: "shadows.enabled",
            label: "Sun shadows",
            kind: SettingKind::Bool,
            range: "true | false",
            step: "-",
            unit: "-",
            advanced: false,
            restart_required: false,
            description: "Master switch for the raster shadow path.",
        },
        SettingMeta {
            path: "shadows.cascades",
            label: "Shadow cascades",
            kind: SettingKind::Int,
            range: "1..=4",
            step: "1",
            unit: "-",
            advanced: true,
            restart_required: false,
            description: "Cascade count over the shadow cover range.",
        },
        SettingMeta {
            path: "shadows.max_distance_m",
            label: "Shadow cover distance",
            kind: SettingKind::Float,
            range: "100..=100000",
            step: "500",
            unit: "m",
            advanced: true,
            restart_required: false,
            description: "Far end of sun-shadow cascade cover.",
        },
        SettingMeta {
            path: "shadows.map_size",
            label: "Shadow map size",
            kind: SettingKind::Int,
            range: "512 | 1024 | 2048 | 4096 | 8192",
            step: "-",
            unit: "px",
            advanced: true,
            restart_required: true,
            description: "Shadow texel grid per cascade (power of two).",
        },
        SettingMeta {
            path: "shadows.normal_bias_m",
            label: "Shadow normal bias",
            kind: SettingKind::Float,
            range: "0..=50",
            step: "0.5",
            unit: "m",
            advanced: true,
            restart_required: false,
            description: "Normal offset against acne on coarse mesh.",
        },
    ]
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn descriptors_cover_mode_switch_and_budgets() {
        let metas = describe();
        let paths: Vec<_> = metas.iter().map(|m| m.path).collect();
        assert!(paths.contains(&"renderer.ray_tracing"));
        assert!(paths.contains(&"renderer.terrain"));
        assert!(paths.contains(&"renderer.terrain_mesh_cells"));
        assert!(paths.contains(&"renderer.hdr"));
        assert!(paths.contains(&"clouds.cast_shadows"));
        assert!(paths.contains(&"raytracing.terrain"));
        assert!(paths.contains(&"atmosphere.ray_steps"));
        let rt = metas
            .iter()
            .find(|m| m.path == "renderer.ray_tracing")
            .unwrap();
        assert!(rt.restart_required);
        let steps = metas
            .iter()
            .find(|m| m.path == "atmosphere.ray_steps")
            .unwrap();
        assert!(!steps.restart_required);
        assert!(!paths.is_empty());
    }
}
