[package]
name = "thessa-server"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license = "GPL-3.0-or-later"
publish = false

[dependencies]
thessa-autopilot = { path = "../../crates/autopilot" }
thessa-autopilot-js = { path = "../../crates/autopilot-js" }
thessa-flight-control = { path = "../../crates/flight-control" }
thessa-sim-core = { path = "../../crates/sim-core" }
thessa-protocol = { path = "../../crates/protocol" }
thessa-flight-authority = { path = "../../crates/flight-authority" }
thessa-flight-net = { path = "../../crates/flight-net" }
thessa-maneuver = { path = "../../crates/maneuver" }
glam.workspace = true
serde.workspace = true
toml.workspace = true
tokio.workspace = true
