[package]
name = "thessa-client"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license = "GPL-3.0-or-later"
publish = false

[dependencies]
thessa-protocol = { path = "../../crates/protocol" }
thessa-sim-core = { path = "../../crates/sim-core" }
bevy.workspace = true
bevy_brp_extras = "0.22.0"
toml.workspace = true
