[package]
name = "thessa-aero-surfaces"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license = "MIT"
publish = false

[dependencies]
glam.workspace = true
serde.workspace = true
thessa-sim-core = { path = "../sim-core" }

[dev-dependencies]
postcard.workspace = true

[[bench]]
name = "compile"
harness = false
