//! Project Thessa reusable authoritative simulation API.
//!
//! The domain crates own deterministic atmosphere/aerodynamics, celestial,
//! trajectory, propulsion, and vehicle models. This facade preserves the
//! original `thessa-sim-core` import surface for downstream crates.

#![forbid(unsafe_code)]

pub use thessa_aero_core::{
    AeroBluntDisc, AeroCase, AeroCoefficientTable, AeroCoefficients, AeroConfig, AeroDiscLoad,
    AeroEnvironment, AeroError, AeroForceBreakdown, AeroGeometry, AeroModel, AeroPanel,
    AeroPanelLoad, AeroResult, AeroSimdScratch, AeroState, AtmosphereComposition, AtmosphereConfig,
    AtmosphereError, AtmosphereSample, BOOM_ANCHOR_PSF, BOOM_OVERPRESSURE_GAIN, BakedAtmosphere,
    BoomCarpet, GasKind, HighSpeedError, PanelAeroModel, PanelSoA, boom_carpet, buffet_fluctuation,
    buffet_gain, diederich_lift_slope, evaluate_batch, vapor_cone_active,
};
pub use thessa_celestial::{
    AU_M, BakedBody, BakedEphemeris, BinaryOrbitConfig, BodyId, BodyState, CelestialConfig, DAY_S,
    EARTH_MASS_KG, EphemerisError, EphemerisFrame, EphemerisScratch, EventScheduler, G,
    GravityError, GravityField, GravityNode, GravityNodeFrame, GravitySourceTree, JUPITER_MASS_KG,
    KeplerOrbit, OrbitConfig, OsculatingElements, ReferenceFrame, SOLAR_MASS_KG, ScheduledEvent,
    ScheduledKind, SimTime, StarConfig, StateVector, SystemConfig, SystemMeta, SystemSpecError,
    TAU, TreeEval, WORLD_TICK_HZ, WORLD_TICK_S, WorldTick, monopole_error_estimate,
    quadrupole_correction, quadrupole_error_estimate,
};
pub use thessa_propulsion::{
    AIR_CP_J_KG_K, AIR_GAMMA, AirAltitudePoint, AirCycle, AirOperatingPoint, AirbreathingSpec,
    AltitudePoint, AuxiliaryPowerUnitCommand, AuxiliaryPowerUnitMount,
    AuxiliaryPowerUnitOperatingPoint, AuxiliaryPowerUnitSpec, AuxiliaryPowerUnitState, BurnPoint,
    ChamberMaterial, ChamberSpec, ColdGasThrusterSpec, CompiledAirbreather,
    CompiledAuxiliaryPowerUnit, CompiledChamber, CompiledColdGas, CompiledElectricMotor,
    CompiledElectricThruster, CompiledEngine, CompiledEstoc, CompiledFusionTorch, CompiledJet,
    CompiledLiquid, CompiledMonoprop, CompiledPistonEngine, CompiledPropeller,
    CompiledPropellerDrive, CompiledPropulsionSystem, CompiledPulsedFusion,
    CompiledShaftPowerSource, CompiledSolid, CompiledTank, CompiledTurbopropDrive, CoolingMode,
    CycleLimits, ESTOC_DEFAULT_SWITCH_MACH_HI, ESTOC_DEFAULT_SWITCH_MACH_LO,
    ESTOC_DEFAULT_TRANSITION_TAU_S, ESTOC_MAX_ROCKET_PC_PA, ESTOC_REINFORCEMENT_FRACTION,
    ElectricMotorPoint, ElectricMotorSpec, ElectricPropellant, ElectricThrusterCommand,
    ElectricThrusterDesign, ElectricThrusterMount, ElectricThrusterPoint, ElectricThrusterSpec,
    EngineCycle, EngineMount, EngineOperatingPoint, EnginePlumeState, EngineSpool,
    EstocAltitudePoint, EstocEjectorSpec, EstocMode, EstocPoint, EstocPrecoolerSpec, EstocSpec,
    FEED_MAX_VELOCITY_MPS, FeedLine, FlightCondition, FusionReaction, FusionTorchCommand,
    FusionTorchMount, FusionTorchOperatingPoint, FusionTorchSpec, GeneratorEfficiencyPoint,
    GeneratorSpec, GeneratorThermalSpec, GimbalEffector, IntakeKind, JetCommand, JetFuel, JetMount,
    JetShaftState, LiquidEngineSpec, MAX_SYSTEM_CHAMBERS, MonopropThrusterSpec, MultiSpoolSpec,
    NTR_COOLDOWN_FRACTION, NTR_DEFAULT_RATED_BURN_S, NTR_DEFAULT_SPECIFIC_MASS_KG_PER_MW,
    NTR_DEFAULT_STARTUP_TAU_S, NTR_INLET_TEMP_K, NTR_KINETIC_EFFICIENCY,
    NTR_MAX_CHAMBER_PRESSURE_PA, NozzleContour, NozzleExitState, NtrFluid, NtrSupplement,
    NuclearThermalSpec, PistonEngineSpec, PistonOperatingPoint, PropDriveAltitudePoint,
    PropDrivePoint, Propellant, PropellantThermo, PropellerDriveCommand, PropellerDriveMount,
    PropellerDriveSpec, PropellerPoint, PropellerSpec, PropulsionError, PropulsionSystemSpec,
    PulsedFusionCommand, PulsedFusionMount, PulsedFusionOperatingPoint, PulsedFusionSpec,
    PulsedFusionState, RCS_DEFAULT_MIN_ON_TIME_S, RCS_DEFAULT_RISE_TIME_S, RcsCluster, RcsMount,
    RcsPulse, RcsThruster, SEPARATION_PRESSURE_RATIO, STANDARD_GRAVITY_MPS2, ShaftBalance,
    ShaftCommand, ShaftPowerSourceSpec, ShaftSpec, ShaftSpool, ShaftTelemetry, SolidGrainGeometry,
    SolidMotorSpec, StarterKind, StarterSpec, StoredPropellant, SystemAltitudePoint, SystemMount,
    SystemOperatingPoint, TankMount, TankResource, TankShape, TankSpec, TurbopropAltitudePoint,
    TurbopropCommand, TurbopropDriveSpec, TurbopropMount, TurbopropOperatingPoint,
    advance_jet_shaft, advance_jet_shaft_loaded, advance_jet_spool, advance_spool,
    analyze_airbreathing, analyze_altitude, analyze_estoc, analyze_propeller_drive,
    analyze_turboprop_drive, characteristic_velocity, effective_propulsive_isp_s, flight_condition,
    mach_from_area_ratio, thrust_coefficient,
};
pub use thessa_trajectory::{
    AdaptiveIntegratorConfig, AffinePropagator, AnalyticError, AnalyticFallback, AnalyticStep,
    COAST_RAILS_EXTEND_CHUNK, COAST_RAILS_HEAD_STEPS, COAST_RAILS_MAX_STEPS,
    COAST_RAILS_MIN_AHEAD_S, COAST_RAILS_POSITION_TOL_M, COAST_RAILS_STEP_S,
    COAST_RAILS_VELOCITY_TOL_MPS, CohortConfig, CohortEval, CohortEvaluator, CohortReport,
    DISPLAY_SCALED_ETA, DISPLAY_SCALED_H_MAX_S, DISPLAY_SCALED_H_MIN_S, DISPLAY_SCALED_MAX_SAMPLES,
    EphemerisTable, GravityPatch, HESSIAN_FROBENIUS_NORM, HESSIAN_REMAINDER, ImpulsiveBurn,
    IntegratorError, IntegratorStats, ModeCoefficients, OnRailsCache, OnRailsWake, PatchError,
    PiecewiseReport, PropagationResult, PropagatorError, SampledPath, SampledPathEnd,
    SensitivityPropagation, StepCoefficients, TABLE_NODE_EVERY_STEPS, TableSnapshot,
    TestParticleState, ThrustArc, ThrustDirection, ThrustPropagationResult, TickIntegratorConfig,
    VelocitySensitivity, VerletConfig, affine_segment_bound, compile_patch, evaluate_cohorts,
    propagate_adaptive, propagate_adaptive_dop853, propagate_adaptive_sensitivity,
    propagate_adaptive_with_burns, propagate_adaptive_with_thrust, propagate_piecewise,
    propagate_sampled_extend, propagate_sampled_verlet, propagate_sampled_verlet_fast,
    propagate_sampled_verlet_scaled, propagate_tick_adaptive, propagate_velocity_verlet, rtn_basis,
};
pub use thessa_vehicle_core::{
    AirlessWheelStructure, AssemblyBodyMassProperties, AssemblyEndpoint, AssemblyError,
    AssemblyJointLoad, AssemblyLinkState, AssemblyOwnership, AssemblyVolume, AuthorityReason,
    AutopilotTier, BatteryPowerTelemetry, BatterySpec, BrakePoint, CabinError, CabinExit,
    CabinExitSide, CabinExitType, CabinMonument, CabinMonumentKind, CabinPressureState, CabinSeat,
    CabinSeatClass, CabinSeatRole, CabinSeatStyle, CabinSuitType, CollisionAxis, CollisionError,
    CollisionGeometry, CollisionMaterial, CollisionPart, CollisionShape, CompiledLandingLeg,
    CompiledWheelChassis, CompiledWheelDrive, ConsumerResourceAllocation, ControlAuthority,
    ControlChannels, ControlCore, ControlHinge, ControlKind, ControlMixing, ControlStation,
    ControlSurfaceActuator, ControlSurfaceDefinition, CrewSuitMode, DockGraph, DockingError,
    DockingKinematics, DockingPortClass, DockingPortSpec, DockingPortState, DockingSession,
    ElectricalPowerCommand, ElectricalPowerError, ElectricalPowerState, ElectricalPowerSystem,
    ElectricalPowerTelemetry, FUEL_CELL_HYDROGEN_LHV_J_KG, FUEL_CELL_OXYGEN_HYDROGEN_RATIO,
    FeedResourceProperties, FleetError, FlightError, FlightForces, FlightStepInput,
    FoldJointRecord, FuelCellPowerTelemetry, FuelCellSpec, HeatShieldMount,
    LandingGearActuatorPoint, LandingGearError, LandingLegMassProperties, LandingLegSpec,
    LandingLegState, LandingShockAbsorberSpec, LandingShockPoint, MAX_LANDING_LEGS, MAX_PARACHUTES,
    MAX_WHEELS_PER_CHASSIS, MOLAR_MASS_AIR_G_MOL, MOLAR_MASS_O2_G_MOL, NamedAssemblyJointStrength,
    NamedAssemblyLink, NamedAssemblyResourceEdge, ParachuteCommand, ParachuteEnvironment,
    ParachuteError, ParachuteLoad, ParachutePhase, ParachuteSpec, ParachuteState, PowerAllocation,
    PowerConsumerSpec, PowerPriority, PowerSystemMassProperties, PressurizedCabin,
    R_DRY_AIR_J_KG_K, RadiatorDeployment, RadiatorSpec, RadiatorTelemetry, ReactionWheelAllocation,
    ReactionWheelBankSpec, ReactionWheelError, ReactorPowerTelemetry, ReactorSpec,
    ReconstructedAssemblyCluster, RigidBodyProperties, RigidBodyState, ShieldError,
    SolarArrayDeployment, SolarArrayPowerTelemetry, SolarArraySpec, SolarArrayTracking,
    SolarFluxSource, SolarOccluder, StatefulPulsedFusionWrench, StatefulTurbopropWrench,
    StrutLoadPoint, ThermalCommand, ThermalError, ThermalFlowCondition, ThermalLinkSpec,
    ThermalMassProperties, ThermalNodeSpec, ThermalNodeTelemetry, ThermalState, ThermalSystem,
    ThermalTelemetry, TireConstruction, TireLoadPoint, TireTangentForcePoint,
    UltracapacitorPowerTelemetry, UltracapacitorSpec, VehicleAssembly,
    VehicleAuxiliaryPowerUnitStep, VehicleDefinition, VehicleError, VehicleId, VehiclePartCommand,
    VehiclePropulsionAllocation, VehicleResourceDemand, VehicleResourceFeedPort,
    VehicleResourcePlan, VehicleResourceState, VehicleWheelMassSplit, WheelBodyMassProperties,
    WheelBrakeSpec, WheelBrakeState, WheelChassisActuatorPoint, WheelChassisMassProperties,
    WheelChassisRetractionSpec, WheelChassisSpec, WheelChassisState, WheelContactLoadPoint,
    WheelDrivePoint, WheelDriveSpec, WheelDriveTractionPoint, WheelLayout, WheelStation,
    WheelStrutSpec, WheelTireSpec, X15StarterProfile, air_groups, allocate_reaction_wheels,
    allocate_reaction_wheels_with_enabled_banks, constant_spin_orientation, control_authority,
    control_surface_commands, crew_groups, default_convective_k, evaluate_flight_forces,
    evaluate_flight_forces_soa, evaluate_flight_forces_with_aero_result, feed_reachable,
    feed_reachable_with_resource_edges, integrate_attitude_step, integrate_rigid_body_duration,
    integrate_rigid_body_duration_sampled, integrate_rigid_body_step,
    integrate_rigid_body_step_soa, integrate_rigid_body_step_with_aero_result,
    x15_contact_geometry,
};

#[cfg(test)]
mod tests;
